import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  // --- GERAL ---
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 24,
    paddingHorizontal: 0,
    paddingBottom: 140
    ,
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 8,
    paddingHorizontal: 8,
    height: 56,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F7FA',
    borderRadius: 20,
    paddingHorizontal: 16,
    height: 48,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#3A6B8E',
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 0,
    fontFamily: 'Poppins_400Regular',
  },
  searchIcon: {
    width: 40,
    height: 40,
    tintColor: '#B3C2CC',
    marginLeft: 8,
  },
  profileIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F3F7FA',
    marginLeft: 8,
  },
  cepText: {
    color: '#5d9cbf',
    textDecorationLine: 'underline',
    marginBottom: 8,
    marginTop: 4,
    fontSize: 15,
    marginLeft: 16,
    fontFamily: 'Poppins_400Regular',
  },
  helloText: {
    fontSize: 32,
    fontWeight: '900',
    color: '#5d9cbf',
    marginBottom: 4,
    marginLeft: 16,
    marginTop: 8,
    fontFamily: 'Poppins_700Bold',
  },
  subtitle: {
    color: '#7BA6C7',
    fontSize: 18,
    marginBottom: 12,
    marginLeft: 16,
    lineHeight: 24,
    fontFamily: 'Poppins_400Regular',
  },
  divider: {
    height: 1,
    backgroundColor: '#E3EAF2',
    marginVertical: 8,
    marginHorizontal: 16,
  },
  sectionTitle: {
    color: '#3A6B8E',
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 8,
    marginLeft: 16,
    fontFamily: 'Poppins_600SemiBold',
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F9FA',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  psychologistIcon: {
    width: 48,
    height: 48,
    marginRight: 12,
    borderRadius: 24,
    backgroundColor: '#D3E6F3',
  },
  cardTextContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  cardTextLine: {
    height: 8,
    backgroundColor: '#D3D7DE',
    borderRadius: 4,
    marginBottom: 6,
    width: '80%',
    fontFamily: 'Poppins_400Regular',
  },
  cardIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  cardIcon: {
    width: 22,
    height: 22,
    marginLeft: 8,
    tintColor: '#7BA6C7',
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 53,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#7BA6C7',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    height: 66,
    paddingHorizontal: 32,
    marginHorizontal: 0,

  },
  bottomFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 56,
    backgroundColor: '#7BA6C7',
  },
  bottomIcon: {
    width: 28,
    height: 28,
    tintColor: '#fff',
    marginHorizontal: 12,
  },
  bottomIconActive: {
    borderBottomWidth: 3,
    borderColor: '#fff',
    borderRadius: 0,
    paddingBottom: 2,
  },

  // --- WELCOME ---
  welcomeContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  welcomeHeaderBackground: {
    height: 500,
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  welcomeContent: {
    flex: 1,
    paddingHorizontal: 30,
    paddingTop: 320,
  },
  welcomeTitle: {
    fontSize: 85,
    textAlign: 'left',
    color: '#5d9cbf',
    fontFamily: 'Poppins_700Bold',
  },
  welcomeSubtitle: {
    fontSize: 30,
    textAlign: 'left',
    color: '#5d9cbf',
    fontFamily: 'Poppins_600SemiBold',
    marginTop: -40,
    marginBottom: 40,
  },
  welcomeSubtitleBold: {
    fontFamily: 'Poppins_700Bold',
  },
  welcomeButton: {
    alignSelf: 'center',
    backgroundColor: '#5d9cbf',
    paddingHorizontal: 50,
    height: 70,
    borderRadius: 22,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  welcomeButtonText: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'Poppins_700Bold',
  },
  welcomeIndicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
    width: '100%',
    paddingBottom: 26,
    gap: 10,
  },
  welcomeIndicator: {
    width: 46,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#bcdff0',
  },
  welcomeIndicatorActive: {
    backgroundColor: '#5d9cbf',
  },

  // --- ONBOARDING 2 ---
  onboardingContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  onboardingHeaderBackground: {
    height: 300,
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  onboardingContent: {
    flex: 1,
    paddingHorizontal: 30,
    paddingTop: 90,
    alignItems: 'center',
  },
  onboardingHero: {
    width: '100%',
    height: 260,
    marginTop : 100,
    marginBottom: 18,
  },
  onboardingTitle: {
    fontSize: 44,
    lineHeight: 55,
    textAlign: 'center',
    color: '#5d9cbf',
    fontFamily: 'Poppins_700Bold',
    marginTop: -40,
    marginBottom: 20,
  },
  onboardingSubtitle: {
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
    color: '#5d9cbf',
    fontFamily: 'Poppins_600SemiBold',
    marginBottom: 30,
  },
  onboardingButton: {
    backgroundColor: '#5d9cbf',
    paddingHorizontal: 26,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  onboardingButtonText: {
    color: '#fff',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Poppins_700Bold',
  },

  // --- ONBOARDING 3 ---
  onboarding3Container: {
    flex: 1,
    backgroundColor: '#98c5de',
  },
  onboarding3Card: {
    flex: 1,
    marginTop: 130,
    marginHorizontal: 0,
    marginBottom: 0,
    borderRadius: 30,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  onboarding3IllustrationCard: {
    height: 270,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  onboarding3Hero: {
    width: '100%',
    height: 210,
  },
  onboarding3Content: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: 10,
    alignItems: 'center',
  },
  onboarding3Title: {
    fontSize: 35,
    lineHeight: 40,
    textAlign: 'center',
    color: '#5d9cbf',
    fontFamily: 'Poppins_700Bold',
    marginTop : 20,
    marginBottom: 25,
  },
  onboarding3Subtitle: {
    fontSize: 17,
    lineHeight: 18,
    textAlign: 'center',
    color: '#5d9cbf',
    fontFamily: 'Poppins_600SemiBold',
    marginBottom: 30,
    marginTop: -15,
  },
  onboarding3PrimaryButton: {
    backgroundColor: '#5d9cbf',
    marginTop: 10,
    paddingHorizontal: 42,
    height: 50,
    borderRadius: 45,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  onboarding3PrimaryButtonText: {
    color: '#fff',
    fontSize: 15,
    textAlign: 'center',
    fontFamily: 'Poppins_700Bold',
  },
  onboarding3OrText: {
    marginTop: 10,
    marginBottom: 6,
    color: '#5d9cbf',
    fontSize: 12,
    fontFamily: 'Poppins_400Regular',
  },
  onboarding3LoginLink: {
    color: '#5d9cbf',
    fontSize: 12,
    fontFamily: 'Poppins_700Bold',
  },
  onboarding3IndicatorsWrap: {
    marginTop: 'auto',
    paddingBottom: 18,
    width: '100%',
  },
  onboarding3Indicator: {
    width: 46,
  },
  
  // --- HEADER / ONDAS ---
  headerBackground: {
    height: 150,
    width: '100%',
    position: 'absolute',
    top: 0,
    zIndex: 0,
  },
  wave: {
    backgroundColor: '#98c5de',
    height: 350,
    width: width * 1.5,
    borderRadius: 800,
    position: 'absolute',
    top: -500,
    left: -(width * 0.25),
    transform: [{ scaleX: 1.2 }],
  },

  // --- CONTEÚDO CADASTRO ---
  scrollContent: {
    paddingTop: 80,
    paddingHorizontal: 24,
    paddingBottom: 16,
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontFamily: 'Poppins_700Bold',
    color: '#5d9cbf',
    marginBottom: 16,
  },

  // --- INPUTS ---
  formArea: {
    width: '100%',
    marginBottom: 10,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#9e9e9e',
    borderRadius: 8,
    height: 48,
    marginBottom: 14,
    paddingHorizontal: 15,
    position: 'relative',
  },
  labelContainer: {
    position: 'absolute',
    top: -8,
    left: 10,
    backgroundColor: '#fff', 
    paddingHorizontal: 5,
    zIndex: 1,
  },
  labelText: {
    color: '#757575',
    fontSize: 12,
    fontFamily: 'Poppins_600SemiBold',
  },
  input: {
    flex: 1,
    height: '100%',
    fontSize: 16,
    color: '#333',
    fontFamily: 'Poppins_400Regular',
  },
  iconContainer: {
    marginLeft: 10,
  },
  iconText: {
    fontSize: 20,
    color: '#757575',
  },

  // --- BOTÕES E LINKS ---
  primaryButton: {
    backgroundColor: '#5d9cbf',
    width: 150,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 15,
  },

  fullPrimaryButton: {
    width: '100%',
    borderRadius: 12,
    height: 52,
    marginBottom: 18,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins_700Bold',
  },
  linkContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  orText: {
    color: '#5d9cbf',
    marginBottom: 5,
    fontSize: 12,
    fontFamily: 'Poppins_400Regular',
  },
  linkText: {
    color: '#5d9cbf',
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
  },
  linkBold: {
    fontFamily: 'Poppins_700Bold',
  },
  secondaryButton: {
    backgroundColor: '#6caecf',
    paddingHorizontal: 20,
    height: 45,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  secondaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontFamily: 'Poppins_600SemiBold',
  },

  // --- ESTILOS ESPECÍFICOS DE LOGIN ---
  loginContainer: {
    flex: 1,
    backgroundColor: '#98c5de',
  },
  loginScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loginBackgroundCircleTop: {
    position: 'absolute',
    top: -100,
    left: -50,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  loginBackgroundCircleBottom: {
    position: 'absolute',
    bottom: -100,
    right: -50,
    width: 400,
    height: 400,
    borderRadius: 200,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  loginCard: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 30,
    paddingVertical: 40,
    paddingHorizontal: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 30,
  },
  loginTitle: {
    fontSize: 28,
    fontFamily: 'Poppins_700Bold',
    color: '#5d9cbf',
    textAlign: 'center',
    marginBottom: 30,
  },
  backButton: {
    backgroundColor: '#eef6fa',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 25,
    elevation: 2,
  },
  backButtonText: {
    color: '#5d9cbf',
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
  },
  backTopLeft: {
    position: 'absolute',
    top: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) + 16 : 56,
    left: 12,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#eef6fa',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#d7eef6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 10,
  },
  onboardingBackTopLeft: {
    top: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) + 28 : 68,
  },
});